### PR TITLE
[Tuist] Tuist Template 세팅

### PR DESCRIPTION
**Pull request by samusesapple**
모듈 생성 명령어
`make module template=ParentModule name=NewModuleName`

*Modules
- Domain
- Core
- UI

### CODE REVIEW

**Review by dely2p — APPROVED** [review]
샘 고생하셨습니다👍

**Review by brightspread — APPROVED** [review]
오 좋습니다!! 고생하셨습니다

**Comment by brightspread** [comment]
error: the package at '/Users/leo/sources/Study/Timery/Timery/Tuist/Timery/Modules/UI/ViewExtension' cannot be accessed (Error Domain=NSCocoaErrorDomain Code=260 "The folder “ViewExtension” doesn’t exist." UserInfo={NSFilePath=/Users/leo/sources/Study/Timery/Timery/Tuist/Timery/Modules/UI/ViewExtension, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x6000002985d0 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}})


뭔가 오류가 나는군요. 한번 찾아볼게요

**Comment by brightspread** [comment]
> error: the package at '/Users/leo/sources/Study/Timery/Timery/Tuist/Timery/Modules/UI/ViewExtension' cannot be accessed (Error Domain=NSCocoaErrorDomain Code=260 "The folder “ViewExtension” doesn’t exist." UserInfo={NSFilePath=/Users/leo/sources/Study/Timery/Timery/Tuist/Timery/Modules/UI/ViewExtension, NSUserStringVariant=( Folder ), NSUnderlyingError=0x6000002985d0 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}})
> 
> 뭔가 오류가 나는군요. 한번 찾아볼게요

오 새로 클론받아서 하니까 잘 됩니다!! 고생하셨습니다

**Pull request closed without merging**
